// screens/SystemReadinessPackagePrintScreen.js
import React, { useEffect, useMemo, useState } from "react";
import { Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { supabase } from "../lib/supabaseClient";

/**
 * System Readiness Package (Print)
 *
 * Purpose: a claim/repair-ready system report.
 * Data source: packages + package_rows generated by generate_system_readiness_package(system_id,...)
 *
 * Expected rows:
 * - section: summary | identity | warranty | assignment | proof | playbook | service
 */
export default function SystemReadinessPackagePrintScreen({ route, navigation }) {
  const packageId = route?.params?.packageId || null;
  const isWeb = Platform.OS === "web";

  const [pkg, setPkg] = useState(null);
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      if (!packageId) {
        setErr("Missing packageId.");
        setLoading(false);
        return;
      }

      setLoading(true);
      setErr("");

      try {
        const { data: pkgData, error: pkgErr } = await supabase
          .from("packages")
          .select("id, asset_id, package_type, title, status, generated_at, totals, snapshot_meta")
          .eq("id", packageId)
          .single();
        if (pkgErr) throw pkgErr;

        const { data: rowData, error: rowErr } = await supabase
          .from("package_rows")
          .select("row_index, row")
          .eq("package_id", packageId)
          .order("row_index", { ascending: true });
        if (rowErr) throw rowErr;

        if (!cancelled) {
          setPkg(pkgData || null);
          setRows(rowData || []);
        }
      } catch (e) {
        if (!cancelled) setErr(e?.message || "Failed to load package.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, [packageId]);

  const onPrint = () => {
    if (!isWeb) return;
    setTimeout(() => window.print(), 50);
  };

  const fmtDate = (v) => {
    if (!v) return "";
    // DB may store as date string YYYY-MM-DD
    const d = new Date(v);
    if (Number.isNaN(d.getTime())) return String(v);
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    const yyyy = d.getFullYear();
    return `${mm}-${dd}-${yyyy}`;
  };

  const safeStr = (v) => (v == null ? "" : String(v));
  const isPresent = (v) => safeStr(v).trim().length > 0;

  const computed = useMemo(() => {
    const items = rows.map((r) => r.row || {});
    const bySection = (section) => items.filter((x) => x.section === section);

    const summary = bySection("summary")[0] || {};
    const identity = bySection("identity")[0] || {};
    const warranty = bySection("warranty")[0] || {};
    const assignment = bySection("assignment")[0] || {};
    const proof = bySection("proof")[0] || {};
    const playbook = bySection("playbook")[0] || {};
    const serviceRows = bySection("service");

    const header = {
      title: pkg?.title || "System Readiness Report",
      assetName: pkg?.snapshot_meta?.asset_name || "Asset",
      systemName: pkg?.snapshot_meta?.system_name || "System",
      generatedLabel: pkg?.generated_at ? new Date(pkg.generated_at).toLocaleString() : "",
    };

    const completeness = {
      hasIdentity: !!summary.has_identity,
      hasWarranty: !!summary.has_warranty,
      hasAssigned: !!summary.has_assigned_keepr_pro,
      proofTotal: Number(summary.proof_total ?? proof.total ?? 0) || 0,
      serviceCount: Number(summary.service_count ?? 0) || 0,
      lastServiceDate: summary.last_service_date || "",
    };

    // Simple readiness score: 0-100 based on identity/warranty/assignment/proof
    const scoreBase =
      (completeness.hasIdentity ? 35 : 0) +
      (completeness.hasWarranty ? 25 : 0) +
      (completeness.hasAssigned ? 20 : 0) +
      (completeness.proofTotal > 0 ? 20 : 0);

    const readiness = {
      score: scoreBase,
      label:
        scoreBase >= 80
          ? "Nicely Documented"
          : scoreBase >= 55
          ? "Needs More Content"
          : "Needs Enrichment",
      missing: [
        !completeness.hasIdentity ? "Identity" : null,
        !completeness.hasWarranty ? "Warranty" : null,
        !completeness.hasAssigned ? "KeeprPro" : null,
        completeness.proofTotal <= 0 ? "Proof" : null,
      ].filter(Boolean),
    };

    return {
      header,
      summary,
      identity,
      warranty,
      assignment,
      proof,
      playbook,
      serviceRows,
      readiness,
    };
  }, [pkg, rows]);

  if (loading) {
    return (
      <View style={styles.screen}>
        <Text style={styles.title}>System Readiness</Text>
        <Text style={styles.muted}>Loading…</Text>
      </View>
    );
  }

  if (err) {
    return (
      <View style={styles.screen}>
        <Text style={styles.title}>System Readiness</Text>
        <Text style={[styles.muted, { marginTop: 8 }]}>{err}</Text>

        <View style={{ marginTop: 16, flexDirection: "row", gap: 10 }}>
          <Pressable onPress={() => navigation.goBack?.()} style={styles.btn}>
            <Text style={styles.btnText}>Back</Text>
          </Pressable>
        </View>
      </View>
    );
  }

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      {isWeb ? (
        <style>{`
          @media print {
      html, body { background: #ffffff !important; color: #111827 !important; }
      * { -webkit-print-color-adjust: exact; print-color-adjust: exact; }

            nav, aside, header, footer,
            [role="navigation"],
            [data-sidebar],
            .sidebar, .SidebarNav, .sidebar-nav, .app-sidebar, .leftNav, .left-nav {
              display: none !important;
              visibility: hidden !important;
            }

            .no-print { display: none !important; }

            html, body, #root { height: auto !important; overflow: visible !important; }
            * { overflow: visible !important; }

            .card, .table, .tr,
            tr, thead, tbody {
              break-inside: avoid;
              page-break-inside: avoid;
            }

            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            @page { margin: 12mm; }
          }
        `}</style>
      ) : null}

      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{computed.header.title}</Text>
        <Text style={styles.metaText}>
          {computed.header.assetName} • {computed.header.systemName}
          {computed.header.generatedLabel ? ` • Generated ${computed.header.generatedLabel}` : ""}
        </Text>

        <View style={styles.actionsRow} className="no-print">
          <Pressable onPress={() => navigation.goBack?.()} style={[styles.btn, styles.btnSecondary]}>
            <Text style={[styles.btnText, styles.btnSecondaryText]}>Back</Text>
          </Pressable>
          {isWeb ? (
            <Pressable onPress={onPrint} style={styles.btn}>
              <Text style={styles.btnText}>Print / Save PDF</Text>
            </Pressable>
          ) : null}
        </View>
      </View>

      {/* Readiness score */}
      <View style={styles.card} className="card">
        <View style={styles.cardRow}>
          <View style={{ flex: 1 }}>
            <Text style={styles.cardTitle}>Readiness</Text>
            <Text style={styles.cardBody}>
              {computed.readiness.label} • Score {computed.readiness.score}/100
            </Text>
            {computed.readiness.missing.length ? (
              <Text style={styles.cardHint}>Missing: {computed.readiness.missing.join(", ")}</Text>
            ) : (
              <Text style={styles.cardHint}>Looks good. This system is well documented.</Text>
            )}
          </View>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>{computed.readiness.score}</Text>
          </View>
        </View>

        <View style={styles.kpiRow}>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Proof</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.proof_total ?? computed.proof.total ?? 0) || 0}</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Service records</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.service_count ?? 0) || 0}</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Last service</Text>
            <Text style={styles.kpiValue}>{isPresent(computed.summary.last_service_date) ? fmtDate(computed.summary.last_service_date) : "—"}</Text>
          </View>
        </View>
      </View>

      {/* Identity */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Identity</Text>
        <View style={styles.grid}>
          <Field label="Manufacturer" value={computed.identity.manufacturer} />
          <Field label="Model" value={computed.identity.model} />
          <Field label="Year" value={computed.identity.year} />
          <Field label="Serial" value={computed.identity.serial_number} />
          <Field label="Location" value={computed.identity.location} />
          <Field label="Installed by" value={computed.identity.installed_by} />
          <Field label="Installed on" value={isPresent(computed.identity.installed_on) ? fmtDate(computed.identity.installed_on) : ""} />
        </View>
        {isPresent(computed.identity.notes) ? (
          <Text style={[styles.cardBody, { marginTop: 10 }]}>{computed.identity.notes}</Text>
        ) : null}
      </View>

      {/* Warranty */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Warranty</Text>
        <View style={styles.grid}>
          <Field label="Provider" value={computed.warranty.provider} />
          <Field label="Policy #" value={computed.warranty.policy_number} />
          <Field label="Starts" value={isPresent(computed.warranty.starts_on) ? fmtDate(computed.warranty.starts_on) : ""} />
          <Field label="Expires" value={isPresent(computed.warranty.expires_on) ? fmtDate(computed.warranty.expires_on) : ""} />
          <Field
            label="Warranty proof"
            value={
              Number.isFinite(Number(computed.warranty.attachment_count))
                ? `${Number(computed.warranty.attachment_count)} item(s)`
                : ""
            }
          />
        </View>
        {isPresent(computed.warranty.coverage_notes) ? (
          <Text style={[styles.cardBody, { marginTop: 10 }]}>{computed.warranty.coverage_notes}</Text>
        ) : null}
      </View>

      {/* Assigned KeeprPro */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Assigned KeeprPro</Text>
        {isPresent(computed.assignment.assigned_keepr_pro_name) ? (
          <>
            <Text style={styles.cardBody}>
              {computed.assignment.assigned_keepr_pro_name}
              {isPresent(computed.assignment.category) ? ` • ${computed.assignment.category}` : ""}
              {isPresent(computed.assignment.location) ? ` • ${computed.assignment.location}` : ""}
            </Text>
            <View style={[styles.grid, { marginTop: 10 }]}>
              <Field label="Phone" value={computed.assignment.phone} />
              <Field label="Email" value={computed.assignment.email} />
              <Field label="Website" value={computed.assignment.website} />
            </View>
          </>
        ) : (
          <Text style={styles.cardHint}>No KeeprPro assigned yet.</Text>
        )}
      </View>

      {/* Proof */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Proof</Text>
        <View style={styles.kpiRow}>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Photos</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.proof_photos ?? computed.proof.photos ?? 0) || 0}</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Files</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.proof_files ?? computed.proof.files ?? 0) || 0}</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Links</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.proof_links ?? computed.proof.links ?? 0) || 0}</Text>
          </View>
          <View style={styles.kpi}>
            <Text style={styles.kpiLabel}>Total</Text>
            <Text style={styles.kpiValue}>{Number(computed.summary.proof_total ?? computed.proof.total ?? 0) || 0}</Text>
          </View>
        </View>
      </View>

      {/* Service history */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Service history</Text>
        {computed.serviceRows.length ? (
          <View style={styles.table} className="table">
            <View style={[styles.tr, styles.th]} className="tr">
              <Text style={[styles.td, styles.thText, { flex: 1.2 }]}>Date</Text>
              <Text style={[styles.td, styles.thText, { flex: 2.2 }]}>Title</Text>
              <Text style={[styles.td, styles.thText, { flex: 1.2 }]}>Category</Text>
              <Text style={[styles.td, styles.thText, { flex: 1.2 }]}>Cost</Text>
              <Text style={[styles.td, styles.thText, { flex: 1.4 }]}>KeeprPro</Text>
            </View>
            {computed.serviceRows.map((r, idx) => {
              const x = r;
              return (
                <View key={x.service_record_id || idx} style={styles.tr} className="tr">
                  <Text style={[styles.td, { flex: 1.2 }]}>{x.performed_at ? fmtDate(x.performed_at) : "—"}</Text>
                  <Text style={[styles.td, { flex: 2.2 }]} numberOfLines={2}>
                    {x.title || "—"}
                  </Text>
                  <Text style={[styles.td, { flex: 1.2 }]}>{x.category || "—"}</Text>
                  <Text style={[styles.td, { flex: 1.2 }]}>{x.cost != null ? `$${Number(x.cost).toFixed(2)}` : "—"}</Text>
                  <Text style={[styles.td, { flex: 1.4 }]}>{x.keepr_pro_id ? "Assigned" : "—"}</Text>
                </View>
              );
            })}
          </View>
        ) : (
          <Text style={styles.cardHint}>No service records yet for this system.</Text>
        )}
      </View>

      {/* Playbook */}
      <View style={styles.card} className="card">
        <Text style={styles.cardTitle}>Maintenance playbook</Text>
        {isPresent(computed.playbook.playbook) ? (
          <Text style={styles.playbookText}>{String(computed.playbook.playbook).trim()}</Text>
        ) : (
          <Text style={styles.cardHint}>No playbook yet. Add one in the system editor to print it here.</Text>
        )}
      </View>

      <Text style={styles.footer}>Keepr • System Readiness Package</Text>
    </ScrollView>
  );
}

function Field({ label, value }) {
  const v = value == null ? "" : String(value);
  const has = v.trim().length > 0;
  return (
    <View style={styles.field}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <Text style={styles.fieldValue}>{has ? v : "—"}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F6F7FB",
  },
  content: {
    padding: 18,
    paddingBottom: 40,
    maxWidth: 1100,
    width: "100%",
    alignSelf: "center",
  },
  header: {
    marginBottom: 12,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 4,
  },
  metaText: {
    fontSize: 13,
    color: "#6B7280",
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  btn: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#2563EB",
  },
  btnSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  btnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 13,
  },
  btnSecondaryText: {
    color: "#111827",
    fontWeight: "800",
    fontSize: 13,
  },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 14,
    marginTop: 12,
    ...(Platform.OS === "web"
      ? { boxShadow: "0 10px 24px rgba(17, 24, 39, 0.06)" }
      : {}),
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  cardBody: {
    color: "#374151",
    fontSize: 13,
    marginTop: 8,
    lineHeight: 18,
  },
  cardHint: {
    color: "#6B7280",
    fontSize: 12,
    marginTop: 6,
  },

  badge: {
    minWidth: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#EEF2FF",
    borderWidth: 1,
    borderColor: "#E0E7FF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  badgeText: {
    color: "#1D4ED8",
    fontWeight: "900",
    fontSize: 16,
  },

  kpiRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    flexWrap: "wrap",
  },
  kpi: {
    minWidth: 120,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  kpiLabel: {
    color: "#6B7280",
    fontSize: 12,
    fontWeight: "700",
  },
  kpiValue: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
    marginTop: 4,
  },

  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 10,
  },
  field: {
    flexGrow: 1,
    flexBasis: 180,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  fieldLabel: {
    color: "#6B7280",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  fieldValue: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 6,
  },

  table: {
    marginTop: 10,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tr: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  th: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: "#F9FAFB",
  },
  thText: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "900",
  },
  td: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },

  playbookText: {
    color: "#111827",
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Platform.OS === "web" ? "ui-monospace, SFMono-Regular, Menlo, monospace" : undefined,
  },

  footer: {
    marginTop: 18,
    textAlign: "center",
    color: "#6B7280",
    fontSize: 12,
  },
});
